### api - hello
POST https://op32h0pf3k.execute-api.ap-southeast-1.amazonaws.com/hello
Content-Type: application/json

{
  "message": "Hello SAM + Java 17"
}


### api - error
POST https://op32h0pf3k.execute-api.ap-southeast-1.amazonaws.com/hello
Content-Type: application/json

{
  "forceError": "true",
  "message": "Hello SAM + Java 17 (2)"
}
